# server config information

http:
  enabled: true
  address: '0.0.0.0'
  port: 8999
  mode: 'release' # `debug` or `release`, default: 'release'

openai:
  token: 'test'

db:
  user: mysql_user
  pass: mysql_password
  host: 127.0.0.1
  port: 3306
  name: db_name
  max_idle_conns: 4
  max_open_conns: 10
  max_life_time: '3600s'
  debug: true
